### ISSUE TITLE
Data required for reproducing on Concode 

### ISSUE THREAD

**Issue by eecshope** [rizwan09/REDCODER#4]
Hello! Thanks for your great work and your code. Currently I want to reproduce your experiments on CONCODE for better understanding. However I can't find the database for retrieval or the output of SCORE-R on CONCODE in your shared Google Drive link. Would you please upload these data? Thanks a lot!

**Comment by rizwan09** [comment]
Hi @eecshope,
Thank you. For Concode, we simply use the union of train, valid, test sets as the retrieval dataset. In Table 8 in the Appendix of our paper, you can find the retrieval corpora size 104k (100k train, 2k valid, 2k test data Stat in Table 1). The reason is the Concoe data is not real code data it it modified data (see example in Appendix B)

**Comment by eecshope** [comment]
Thanks for your reply. I'll try that following your instructions.
